//<auto-generated />
using System.Runtime.InteropServices;

namespace Genbox.FastCodeSign.Internal.Native.Win32;

[StructLayout(LayoutKind.Explicit)]
internal struct SUBJECT_CHOICE_UNION
{
    [FieldOffset(0)]internal IntPtr pSignerFileInfo;
    [FieldOffset(0)]internal IntPtr pSignerBlobInfo;
}